# Generated by Django 4.1.2 on 2023-04-12 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.ManyToManyField(null=True, related_name='project_developer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='quality_assurance',
            field=models.ManyToManyField(null=True, related_name='project_qa', to=settings.AUTH_USER_MODEL),
        ),
    ]
