# Generated by Django 4.1.2 on 2023-04-13 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
