# Generated by Django 4.1.2 on 2023-04-18 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bug_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='assignee',
        ),
        migrations.AddField(
            model_name='bug',
            name='assignee',
            field=models.ManyToManyField(null=True, related_name='assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
